# listen address
listen_address = "localhost:8888"

# DB server address
db_address = "localhost:8889"

# monitoring server address
mon_address = "localhost:9000"

#listen protocol
listen_protocol = "NDTP"

#log level
log_level = "trace"

# list of data consumers
consumers_list = ["vis1", "vis2", "vis3"]

# test mode provides more detailed logs but reduces system performance
test_mode = false

#key expire sec
key_ex = 20

#period check not confirmed ms
period_notconf_data = 60000

#period old data ms
period_old_data = 55000

#period check old data sec
period_check_old = 1

#timeout close sec
timeout_close = 5

#timeout error reply sec
timeout_error_reply = 5

#timeout reconnect sec
timeout_reconnect = 10

[vis1]
# consumer's unique id
id = 1
# consumer's address
address = "10.20.30.41:5555"
# consumer's protocol
protocol = "EGTS"
# is consumer a master system
master = false

[vis2]
id = 2
address = "10.20.30.41:5556"
protocol = "NDTP"
master = true


[vis3]
id = 3
address = "10.20.30.41:5557"
protocol = "NDTP"
master = false