# listen address
listen_address = "localhost:8888"

# DB server address
db_address = "localhost:8889"

# monitoring server address
mon_address = "localhost:9000"

#listen protocol
listen_protocol = "NDTP"

#log level
log_level = "trace"

# list of data consumers
consumers_list = ["vis1", "vis2", "vis3"]

# test mode provides more detailed logs but reduces system performance
test_mode = false

#key expire sec
key_ex = 20

#period check not confirmed egts ms
period_notconf_data_egts = 60000

#period check not confirmed ndtp ms
period_notconf_data_ndtp = 60000

#period old data ms
period_old_data = 1000

#period check old data egts sec
period_check_old_egts = 60

#period check old data ndtp sec
period_check_old_egts = 60

#timeout close sec
timeout_close = 5

#timeout error reply sec
timeout_error_reply = 5

#timeout reconnect sec
timeout_reconnect = 10

# old packets number to send before waiting confirmations (for egts system)
max_to_send_old_egts = 600000

# unloading limit old packages from the database (for egts system)
limit_old_egts = 600000

# old packets number to send before waiting confirmations (for ndtp system)
max_to_send_old_ndtp = 600

# unloading limit old packages from the database (for ndtp system)
limit_old_ndtp = 600

# redis pool max idle connections
redis_max_idle = 220

#redis pool max active connections
redis_max_active = 220

# period send old packets without realtime data
period_send_old_ndtp = 30

[vis1]
# consumer's unique id
id = 1
# consumer's address
address = "10.20.30.41:5555"
# consumer's protocol
protocol = "EGTS"
# is consumer a master system
master = false

[vis2]
id = 2
address = "10.20.30.41:5556"
protocol = "NDTP"
master = true


[vis3]
id = 3
address = "10.20.30.41:5557"
protocol = "NDTP"
master = false